from CursoEmVideo.Mundo03_Estruturas_Compostas.Exercicios.exercicios_modulo.exe111_modulo.utilidadescev import moeda
from CursoEmVideo.Mundo03_Estruturas_Compostas.Exercicios.exercicios_modulo.exe111_modulo.utilidadescev import dado
